# frozen_string_literal: true

source "https://rubygems.org"

gem "ratalada", "~> 2.1.0"
gem "falcon"
gem "rack-session"
gem "railties"
gem "activerecord"
gem "actionpack"
gem "sqlite3"
gem "doorkeeper"
gem "doorkeeper-openid_connect"
gem "omniauth_openid_connect"
gem "bcrypt"
