name: Github Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages:
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment:
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
        working-directory: docs

    - name: Build documentation
      timeout-minutes: 5
      working-directory: docs
      run: bundle exec jekyll build --baseurl /ratalada -d _site
      env:
        JEKYLL_ENV: production

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: docs/_site

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
